implementation_name: sierraleone

initial_database_url: https://raw.githubusercontent.com/Bahmni/bahmni-package/master/openmrs/resources/openmrs_clean_dump.sql
implementation_config_repository: https://github.com/PIH/wellbody-config.git
implementation_config_repository_version: master

implementation_distro_repository: https://github.com/PIH/openmrs-module-pihsierraleone.git
implementation_distro_repository_version: master
