# required by Bahmni installer

implementation_name: sierraleone
bahmni_ntp_timezone: America/New_York

bahmni_repo_url: https://bahmni-repo.twhosted.com/rpm/bahmni/
bahmni_installer: bahmni-installer-0.80-139.noarch.rpm
bahmni_installer_directory: /etc/bahmni-installer
bahmni_deployment_artifacts: /etc/bahmni-installer/deployment-artifacts

mysql_root_password: password
openmrs_db_username: openmrs
openmrs_db_password: password
openmrs_server_options: "-Xms1024m -Xmx2048m -XX:PermSize=512m -XX:MaxPermSize=1024m"

# used by pih-deployment

initial_database_url: https://raw.githubusercontent.com/Bahmni/bahmni-package/master/openmrs/resources/openmrs_clean_dump.sql
implementation_config_repository: https://github.com/PIH/wellbody-config.git
implementation_config_repository_version: master

implementation_distro_repository: https://github.com/PIH/openmrs-module-pihsierraleone.git
implementation_distro_repository_version: master
