---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars_files:
    - ../group_vars/local


  tasks:
  - name: install required packages
    yum: pkg={{ item }} state=installed
    with_items:
        - unzip
        - tar
        - wget
        - curl

  - name: copy mysql dump to /etc/bahmni-installer/deployment-artifacts    
    get_url: url="{{ bahmni_implementation_repo_url }}/mysql_dump.sql" dest=/etc/bahmni-installer/deployment-artifacts    

  - name: copy implementation config    
    get_url: url="{{ bahmni_implementation_repo_url }}/{{ implementation_name }}_config.zip" dest=/etc/bahmni-installer/deployment-artifacts

  - name: Create implementation directory
    file: path={{ bahmni_deployment_artifacts }}/{{ implementation_name }}_config state=directory

  - name: Extract implementation config    
    unarchive: src={{ bahmni_deployment_artifacts }}/{{ implementation_name }}_config.zip dest={{ bahmni_deployment_artifacts }}/{{ implementation_name }}_config copy=no

