---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars_files:
    - ../group_vars/setup.yml


  tasks:
  - name: install required packages
    yum: pkg={{ item }} state=installed
    with_items:
        - unzip
        - tar
        - wget
        - curl
        - git

  - name: copy mysql dump from custom url to /etc/bahmni-installer/deployment-artifacts
    get_url: url="{{ initial_database_url }}" dest=/etc/bahmni-installer/deployment-artifacts/mysql_dump.sql
    when: initial_database_url is defined

  - name: copy mysql dump from conventional url to /etc/bahmni-installer/deployment-artifacts
    get_url: url="{{ bahmni_implementation_repo_url }}/mysql_dump.sql" dest=/etc/bahmni-installer/deployment-artifacts/mysql_dump.sql
    when: initial_database_url is undefined

  - name: clone implementation config from github
    git: repo={{ implementation_config_repository }} version={{ implementation_config_repository_version }} dest={{ bahmni_deployment_artifacts }}/{{ implementation_name }}_config
    when: implementation_config_repository is defined

  - name: copy implementation config from conventional url
    get_url: url="{{ bahmni_implementation_repo_url }}/{{ implementation_name }}_config.zip" dest=/etc/bahmni-installer/deployment-artifacts
    when: implementation_config_repository is undefined

  - name: Create implementation directory
    file: path={{ bahmni_deployment_artifacts }}/{{ implementation_name }}_config state=directory
    when: implementation_config_repository is undefined

  - name: Extract implementation config    
    unarchive: src={{ bahmni_deployment_artifacts }}/{{ implementation_name }}_config.zip dest={{ bahmni_deployment_artifacts }}/{{ implementation_name }}_config copy=no
    when: implementation_config_repository is undefined
