---
- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars_files:
    - ../group_vars/{{ implementation_name }}-config.yml
  tasks:

  # PRE-INSTALLATION ACTIVITIES

  - name: install required packages
    yum: pkg={{ item }} state=installed
    with_items:
        - unzip
        - tar
        - wget
        - curl
        - git
    tags: [pre-install]

    # Specify where to get the initial database SQL

  - debug: msg="Pre-installation of {{ implementation_name }}"
    tags: [pre-install]
      
  - name: copy mysql dump from custom url to /etc/bahmni-installer/deployment-artifacts
    get_url: url="{{ initial_database_url }}" dest=/etc/bahmni-installer/deployment-artifacts/mysql_dump.sql
    when: initial_database_url is defined
    tags: [pre-install]

    # Specify where to get the configuration.  There are several options:

    # Option 1: Clone from github (must specify both repository and version)

  - name: clone implementation config from github
    git: repo={{ implementation_config_repository }} version={{ implementation_config_repository_version }} dest={{ bahmni_deployment_artifacts }}/{{ implementation_name }}_config
    when: implementation_config_repository is defined
    tags: [pre-install]

    # Option 2: Download as a zip file from remote URL (resource must be named {{ implementation_name }}_config.zip)

  - name: copy implementation config as a zip from a url
    get_url: url="{{ implementation_config_zip_url }}" dest=/etc/bahmni-installer/deployment-artifacts
    when: implementation_config_zip_url is defined
    tags: [pre-install]

  - name: Create implementation directory
    file: path={{ bahmni_deployment_artifacts }}/{{ implementation_name }}_config state=directory
    when: implementation_config_zip_url is defined
    tags: [pre-install]

  - name: Extract implementation config    
    unarchive: src={{ bahmni_deployment_artifacts }}/{{ implementation_name }}_config.zip dest={{ bahmni_deployment_artifacts }}/{{ implementation_name }}_config copy=no
    when: implementation_config_zip_url is defined
    tags: [pre-install]

    # Option 3:  When developing, it is useful to be able to copy the implementation config from another folder

  - name: Copy implementation config
    copy: src={{ implementation_config_dir }} dest={{ bahmni_deployment_artifacts }}/{{ implementation_name }}_config mode=755 owner=bahmni group=bahmni
    when: implementation_config_dir is defined
    tags: [pre-install,update-config]

    # POST-INSTALLATION ACTIVITIES

  - debug: msg="Post-installation of {{ implementation_name }}"
    tags: [post-install]