---
- hosts: 127.0.0.1
  sudo: yes
  
  vars_files:
      - ../../../group_vars/production
  tasks:
  - name: Creating groups
    group: name="{{item}}"
    with_items: groups_to_create
    tags: ['groups','configuration']

  - name: Creating Users
    user: name="{{item.username}}" state=present
        group="{{item.group if groups_to_create else default_users_group}}"
        groups="{{item.groups | join(',') if groups_per_user else default_users_group}}"
        shell="{{item.shell if shell is defined else users_default_shell}}"
        password="{{item.password}}"
        comment="{{item.name}}"
        createhome={{'no' if users_homedirs else 'yes'}}
    with_items: "{{users}}"
    tags: ['create_users','configuration']

  - name: Force users to change password on login
    shell: chage -d 0 {{ item.username }}
    with_items: "{{users}}"
    tags: password_change

  - name: Delete users
    user: name={{item.username}} state=absent remove=yes
    with_items: users_deleted
    tags: ['delete_users','configuration']

  - name: Delete user created group
    group: name="{{item.username}}" state=absent
    with_items: users_deleted
    tags: ['delete_users','delete_groups','configuration']
